### ISSUE TITLE
name of my new model

### ISSUE THREAD

**Issue by mody4** [CODAIT/max-central-repo#22]
Please fill out the relevant template with as much detail as you can provide.

## New Model Proposal 
 1. Model Name:
 2. Domain (e.g., Computer Vision, Natural Language Processing, Audio):
 3. Application (e.g., Object Detection, Image Classification):
 4. Model Detailed Description:
 5. Model License:
 6. Model Training Data Link and License:
 7. Paper Reference if any:
 8. Owner details (Name and Email):
 9. License for Model:
10. Model Framework:
11. Source repository (if applicable):

## Code Change
 1. Which model(s) are affected?

    If this is about a particular MAX model, please close this page and ask in their respective repository. You can find a list of the repositories [here](https://github.com/CODAIT/max-central-repo/blob/master/max-model-status.md).

 2. If it is performance issue, describe the bug:
 3. Link to the code to reproduce the issue:
 4. System information (OS/Framework + version/Python version):
 5. Include logs to diagnose the problem:
 6. Link to the solution:
 7. Link to the test cases:
 
## Feature Request
 1. Which model(s) is this request for?

    If this is about a particular MAX model, please close this page and ask in their respective repository. You can find a list of the repositories [here](https://github.com/CODAIT/max-central-repo/blob/master/max-model-status.md).

 2. Is there already an existing implementation in case of a feature request?
 3. What will be the benefit of the change?
 4. Will this change impact the current API?
 5. Link to the solution:
 6. Link to the test cases:

**Comment by xuhdev** [comment]
Empty issue. Feel free to open another issue. Closed now.
